---
- name: Install MariaDB package
  yum:
    name: '{{item}}'
    state: latest
  with_items:
    - mariadb-server
    - MySQL-python
    - libsemanage-python

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
...